# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 79b807a435da24e56c6350f006de1dd303889b83d43312fb024db6881904858a74a7d2e1d1c7175080082f19eb7690cbe1a4737c2b63f789b67c7c958e8c82e5

test:
  secret_key_base: a8a743473d6b6aa533520c783b96768f132f5b3bf925e4a5e0ff3d62f939bf5f606d22dd0507b213402bbd0e90a087d8219e6f66bd117d3358a1976a6a3fe070

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
